urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'canvases.views.home', name='home'),
    # url(r'^canvases/', include('canvases.foo.urls')),

    #home
    url(r'^$', 'canvases.posts.views.home'),

    # === USERS ===


    # AUTHENTICATION

    #login page
    url(r'^login/$', 'canvases.users.views.login_user'),

    #logout
    url(r'^logout/$', 'canvases.users.views.logout_user'),

    #login post
    url(r'^postlogin/$', 'canvases.users.views.authenticate_user'),

    #register new user
    url(r'^register/$', 'canvases.users.views.register'),

    #submit registration
    url(r'^postregister/$', 'canvases.users.views.create_user'),

    #generic login required page
    url(r'^login_required/$', 'canvases.users.views.login_required'),

    # INFO

    #user page (generic)
    #TODO this should redirect to the page below...)
    url(r'^users/([a-zA-Z0-9]+)/$', 'canvases.users.views.user_detail'),

    url(r'me/', 'canvases.users.views.current_user_detail'),


    # === POSTS ===

    #write new post
    url(r'^writepost/$', 'canvases.posts.views.writepost'),

    #submit it
    url(r'^postsubmit/$', 'canvases.posts.views.newpost'),

    #post detail
    url(r'^([0-9]+)/$', 'canvases.posts.views.detail'),

    #edit post
    url(r'^([0-9]+)/edit/$', 'canvases.posts.views.edit_post'),

    #edit post, POST
    url(r'^postedit/$', 'canvases.posts.views.edit_post_post'),

    #view all posts

    #most recent
    url(r'^posts/$', 'canvases.posts.views.posts'),

    #specific page
    url(r'^posts/([0-9]+)/$', 'canvases.posts.views.posts_page'),

    # === GROUPS ===

    #view all groups
    url(r'^allgroups/$', 'canvases.groups.views.group_view_all'),

    #new group
    url(r'^newgroup/$', 'canvases.groups.views.group_new'),

    #new group POST
    url(r'^postnewgroup/$', 'canvases.groups.views.group_new_post'),

    #maintain group
    url(r'^group/([0-9]+)/$', 'canvases.groups.views.group_change'),

    #add member POST
    url(r'^group/([0-9]+)/addmember/$', 'canvases.groups.views.group_add_member_post'),

    #add member AJAX POST
    url(r'^addmembertest/$', 'canvases.groups.views.ajax_test'),


    #add post to group
    url(r'^group/([0-9]+)/newpost/$', 'canvases.posts.views.new_post_group'),

    #add post to group POST
    url(r'^group/([0-9]+)/newpostpost/$', 'canvases.posts.views.new_post_group_post'),


    # === COMMENTS ===

    #leave new comment
    url(r'^leavecomment/$', 'canvases.posts.views.leave_comment'),
    


    # Admin stuff
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

groups/models.py
from django.db import models
from django.contrib.auth.models import User

class Group(models.Model):
  name        = models.CharField(max_length=100)
  description = models.TextField()
  users       = models.ManyToManyField(User)
  visible     = models.BooleanField()

templates/allgroups.html
{% extends "skeleton.html" %}

{% block title %}Home page{% endblock %}

{% block content %}
  <h1>View all groups</h1>

  <ol>
  {% for group in groups %}
    <li>
	  <a href="/group/{{ group.id }}/"><b>{{ group.name }}</b></a>{% if group.description %}:
	  <i>{{ group.description }}</i>{% endif %}
	</li>
  {% endfor %}
  </ol>

{% endblock %}

templates/allposts.html
{% extends "skeleton.html" %}

{% block content %}
    <h1>View all posts.</h1>

    {% for post in posts %}
      <b>{{ post.title }}</b> <br /> {{ post.content }} <br />
        <div class="small">
          (<a href = "/{{ post.id }}">Comments ({{ post.num_comments }})</a> | Brought to you by <a href="/users/{{ post.creator }}">{{ post.creator }}</a>.)
        </div>
    {% endfor %}

    Pages: 
    {% for link in pages %}
        <a href="{{ link.link }}">{{ link.number }}</a>
    {% endfor %}
{% endblock %}

templates/changegroup.html
<html>
  <body>
    <h1> {{ group.name }} </h1>
    <i> {{ group.description }} </i> <br />

    Members: 
    {% for member in group.users.all %}
      <a href="/users/{{ member.username }}">{{ member.username }}</a>
      {% if not forloop.last %},{% endif %}
    {% endfor %} <br />

    <p />

    <form action="/group/{{ group.id }}/addmember" method = "post">
      {% csrf_token %}
      Add member: <input type="text" name="name" />
      <input type="submit" value="Add!" />
    </form>

    <b> Recent posts: </b> <a href="/group/{{ group.id }}/newpost">(Add new post)</a> <br />

    {% for post in posts %}
      {{ post.title }}<br />
    {% endfor %}

  </body>
</html>

templates/current_user_detail.html
{% extends "skeleton.html" %}

{% block content %}
    <h1>Your main page!</h1>

    <p>You are logged in as {{ user.username }}. Want to <a href="/logout">log out?</a></p>


    Groups you belong to: 
    {% for group in user.group_set.all %}
      <a href="/group/{{ group.id }}">{{ group.name }}</a>{% if not forloop.last %},{% endif %}
    {% endfor %}

    <p><a href="/newgroup">Make a new group.</a></p>
    <p><a href="/allgroups">View all groups.</a></p>


    <h2>Recent posts:</h2>
    {% for post in posts %}
      <li>
	    {{ post.title }} 
        <a href="/{{ post.id }}/edit">Edit</a>
      </li>
    {% endfor %}

    <!--
    Pages: 
    {% for link in pages %}
      <a href = "{{ link.link }}">{{ link.number }}</a>
    {% endfor %}
    -->
{% endblock %}

templates/detail.html
{% extends "skeleton.html" %}

{% block content %}
    <h1>{{ post.title }}</h1>
    {{ post.content }}
    
    {% if user == post.creator %}
      <a href = "/{{ post.id }}/edit">Edit</a> <br />
    {% endifequal %}

    Comments: <br />

      {% for comment in comments %}
        <div class="comment">
          <div class="commentbody">
            <li> {{ comment.content }}  -- <a href="/users/{{ comment.creator }}">{{ comment.creator }}</a> <br />
          </div>
        </div>
      {% endfor %}
    <br />

    Leave a comment: <br />

    <form action="/leavecomment/" method = "post">
      {% csrf_token %}
      <textarea name="content" cols="60%" rows="10" tabindex="4"></textarea>
      <input type="hidden" name="postid" value="{{ post.id }}" />
      <input type="submit" value="Comment!" />
    </form>
{% endblock %}

templates/edit.html
{% extends "skeleton.html" %}

{% block content %}
	<h1>Edit &ldquo;{{ post.title}}&rdquo;</h1>

	<form action="/postedit/" method = "post">
		{% csrf_token %}
		<textarea name="content" cols="60%" rows="10" tabindex="4">{{ post.content }}</textarea>
		<input type="hidden" name="postid" value="{{ post.id }}" />
		<input type="submit" value="Edit!" />
	</form>
{% endblock %}

templates/group_detail.html
{% extends "skeleton.html" %}

{% block title %}Home page{% endblock %}

{% block scripts %}

  <script>
    $(function() {
      var autocomplete = {{ all_users|safe }};

      $( "#nameinput" ).autocomplete({
        source: autocomplete
      });

      $("#sendrequest").click(function(){
        $.post("/group/{{ group.id }}/addmember/" 
              , { id   : {{ group.id }}
                , name : $("#nameinput").val()
                }
              , function(data) {
                  /* Append name to list. */
                  data = "<a href='/users/" + data + "'>" + data + "</a>"
                  $("#newmembers").html(", " + data)
                }
              );
      }); 

    });


  </script>
{% endblock %}

{% block content %}

	<h1> {{ group.name }} </h1>
	{% if group.description %}
		<p><em>{{ group.description }}</em></p>
	{% endif %}

	<p>Members: 
	{% for member in group.users.all %}
	  <a href="/users/{{ member.username }}">{{ member.username }}</a>{% if not forloop.last %},{% endif %}
	{% endfor %}
	</p>



	<form action="/group/{{ group.id }}/addmember/" method = "post">
	  {% csrf_token %}
	  Add member: <input type="text" name="name" id="nameinput" />
	  <input type="button" id="sendrequest" value="Add!" />
	</form>

	<b>Recent posts:</b> <a href="/group/{{ group.id }}/newpost">(Add new post)</a> <p>

	{% for post in posts %}
	  <b>{{ post.title }}</b><br/>
	  {{ post.content }}<br/>
	  <a href="/{{ post.id }}">Comments</a>
	  <p/>
	{% endfor %}

{% endblock %}

templates/index.html
{% extends "skeleton.html" %}

{% block title %}Home page{% endblock %}

{% block content %}
	<h1>{{ SITE_NAME }}</h1>

	<form id="signup">
		<div class="inner">
			<div><label for="username">Username: </label><input id="username" type="text"/></div>
			<div><label for="password">Password: </label><input id="password" type="password"/></div>
			<div><a class="button" href="/">Sign Up ›</a></div>
		</div>
	</form>
	<h2>Latest posts</h2>
	<ul>
		{% for post in recent_posts %}
		<li>{{ post.title }}</li>
		{% endfor %}
	</ul>
	<h2>Latest groups</h2>
	{% for group in recent_groups %}
	<li>{{ group.title }}</li>
	{% endfor %}
{% endblock %}

templates/login.html
{% extends "skeleton.html" %}

{% block content %}
<h1>{{ SITE_NAME }}</h1>

<form action="/postlogin/" method = "post">
	{% csrf_token %}
	Name: <input type="text" name="username" /> <br />
	Password: <input type="password" name="password" /> <br />

	<input type="submit" value="Log In!" />
</form>
{% endblock %}

templates/login_required.html
Login is required to do that.

templates/register.html
{% extends "skeleton.html" %}

{% block content %}
    <h1>Register</h1>

    <form action="/postregister/" method = "post">
      {% csrf_token %}
      <div>Name: <input type="text" name="username"/></div>
      <div>Email*: <input type="text" name="email"/></div>
      <div>Password: <input type="password" name="password"/></div>
      <div><input type="submit" value="Register!"/></div>
    </form>
    <div class="subscript">
        *We will never email you. We don't even know why we ask for your address.
    </div>
{% endblock %}

templates/skeleton.html
<!DOCTYPE html>
<html>
  <head>
    <!-- js -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.11/jquery-ui.min.js"></script>
    <script>
    /* ensure that CSRF token is sent with AJAX requests */
      $('html').ajaxSend(function(event, xhr, settings) {
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie != '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) == (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
            // Only send the token to relative URLs i.e. locally.
            xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
        }
      });
    </script>
	{% block scripts %}{% endblock %}
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/main.css"/>
    <title>{% block title %}{% endblock %}{{ SITE_URL }}</title>
  </head>
  <body>
	<div id="nav" class="small">
		<div class="centercolumn">
		{% if user.is_authenticated %}
			<div class="right">
				Hello, {{ user }}.
				<a href="/logout/">log off</a>
			</div>
		{% else %}
			<div class="right">
				<form action="/postlogin/" method="post">
					{% csrf_token %}
					<label for="loginuser">Username: </label><input type="text" name="username" id="loginuser"/>
					<label for="loginpass">Password: </label><input type="password" name="password" id="loginpass"/>
					<input class="button" type="submit" value="Log in"/>
				</form>
			</div>
		{% endif %}
			<div class="clear"></div>
		</div>
	</div>
	<div class="centercolumn">
	    {% block content %}{% endblock %}
	</div>
  </body>
</html>

templates/user_detail.html
{% extends "skeleton.html" %}

{% block content %}
    <h1>Who is this {{ username }} guy, anyway?</h1>

	<p>
    {% if is_current_user %}
      Why, that appears to be you!
    {% else %}
      I dunno either. But here are some of their posts: 
    {% endif %}
    </p>

    {% for post in posts %}
      <li>{{ post.title }} 
      {% if is_current_user %}
        <a href="/{{ post.id }}/edit">Edit</a>
      {% endif %}
      </li>
    {% endfor %}

    <!--
    Pages: 
    {% for link in pages %}
      <a href = "{{ link.link }}">{{ link.number }}</a>
    {% endfor %}
    -->
{% endblock %}

templates/writepost.html
{% extends "skeleton.html" %}

{% block content %}
    <h1>This is the newpost page.</h1>

    <form action="{{ posturl }}" method = "post">
      {% csrf_token %}
      <div>Title: <input type="text" name="title"/></div>
      <textarea name="content" cols="60%" rows="10" tabindex="4"></textarea>

      <div><input type="submit" value="Post!"/></div>
    </form>
{% endblock %}